---
title: "Who are ASM journals: an analysis of authors, reviewers, and editors"
author: "Ada Hagan"
date: "October 30, 2018"
output: html_document
---
```{r, setup}
source("code/analysis_functions.R")
source("code/load_data.R")
source("code/get_plot_options.R")
```

#Abstract

#Introduction

  Scientific societies play an integral role in the formation and maintanence of scientific communities. They host conferences that provide a forum for knowledge exchange and networking, as well as opportunities for increased visibility as a researcher. Scientific societies also frequently publish the most reputable journals in their field, facilitating the peer review process to vet new research submissions. As such, societies have great power to set both professional and scientfic norms in their community by choosing what behaviors are rewarded and what types of research are accepted for publication. Given that the authorship of such research publications is a key criterium for hiring and promotion processes in academic circles, it is a coveted measure of success. Accordingly, editors and reviewers of research journals have a substantial influence over the futures of hopeful authors. While the membership of scientific societies is likely to reflective of all those who participate in the field, regardless of career track, the gatekeepers for peer review (reviewers and editors) are more reflective of the academy than the society of a whole.

  Evidence has accumulated over the decades that academic research has a representation problem. With regards to gender, while at least 50% of biology Ph.D. graduates are women, the number of women in postdoctoral positions and tenure-track positions are less than 40 and 30%, respectively @article{sheltzer_elite_2014}. Studies examining other metrics such as race and ethnicity find that less than 10% of all science and engineering doctorates were awarded to underrepresented minorities, while less than 25% of science and engineering doctorates in early career academia identify as non-white (NSF ADVANCE, 2014). Predictabily, the disparities increase alongside academic rank, a phenomenon known as hierarchical segregation @article{potvin_diversity_2018}. There have been many proposed reasons for these disparities (particularly against women) that include biases in training and hiring, the impact of children on career trajectories, a lack of support for primary caregivers, and a lack of recognition, which culminate in reduced productivity as measured by research publications. 

  Recently, scientific societies and publishers have begun examining their own data to evaluate representation of, and bias agains, women and minorities in their peer review processes. The American Geological Union found that while the acceptance rate of women-authored publications was greater than that for publications authored by men, women submitted fewer manuscripts than men and were used as reviewers only 20% of the time (Lerback, 2017). Fox et al., have found that for the journal _Functional Ecology_, the proportion of women invited to review depended on the gender of the editor and that editors were more likely to invite individuals from their own geographic region to review (Fox, 2016). Despite the disproportional representation of lead women authors, several studies have concluded that there is no significant bias aginst papers authored by women (C&W, 2011; Fox, 2016; Handly, 2015; Edwards, 2018). Conversely, a preprint study of the peer review process at eLife found statistically significant bias against women, particularly from review groups composed of all men (Murray, 2018). Studies looking at the geographic distribution of authors have also found poor representation of non-Western countries and statistically significant bias based on geography and percieved "non-english speaking" authors (Murray, 2018; Handley, 2015; Edwards, 2018).
  
  However, gender and geographic representation can differ dramatically according to the scientific field and no studies to-date seem to have investigated academic publishing in the field of microbiology (Elseiver report). [Stats on ASM size/membership that make it a good study system]. In its mission statement, the American Society for Microbiology (ASM) notes that it is "an inclusive organization, engaging with and responding to the needs of its diverse constituencies." The ASM also pledges to "address all members' needs through development and assesment of programs and services" while the ASM Journals Department boasts of "quality peer review and editorial leadership." Therefore, in an effort to be transparent with ASM journal patrons and ASM members, the purpose of this study is to describe who are ASM journals. In other words, what is the gender and geographic representation of authors, reviewers and editors during peer review at ASM journals? Additionally, does that representation reflect the field of microbiology and ASM members?

#Results

##Validating gender analysis

We recognize that biological sex (male/female) is different from the gender that an individual presents as (man/woman), which is also distinct from the gender(s) that one may self-identify as. For the purposes of this manuscript, we choose to focus on the presenting gender (man/woman/unclear) based on their first names and/or appearance (for editors). In the interest of transparency, we include those individuals whose names don't allow a high degree of confidence for gender assignment in the "unclear" category. These individuals are considered to have gender neutral names, primarily due to genderless naming conventions. 

  + predicted vs percieved gender of editors
  
  + predicted names by country (countries associated w. NA genders?)
  
  + Nicole's dataset?

##Gender (pre or post publication?)

  This study uses the data from manuscripts submitted to ASM journals that had a decision rendered between January 2012 and August 2018. 
   + gender of all editors over time
   
   + breakdown into editor type: e.g., EiC, senior, associate? (ed_gender_time.R)
   
   + gender of all reviewers over time (reviewer_gender_time.R)
   
   + gender of all senior/coresponding authors over time (last_gender_time.R/corres_gender_time.R)
   
   + gender of all first authors over time (first_gender_time.R)
   
   + gender of middle authors over time (middle_gender_time.R)
   
   + gender of all authors (auth_gender_time.R)
   
   + proportion of gender at each stage: e.g., author, reviewer, editor by type
   
   + invited manuscripts by gender
   
   + male/female dominated categories? journals?
   
##Geographic
   
   + geographic origin of all editors over time
   
   + breakdown into editor type: e.g., EiC, senior, associate?
   
   + geographic dist of all reviewers over time
   
   + geographic of all senior/coresponding authors over time
   
   + geographic of all first authors over time
   
   + geographic of all authors
   
   + proportion of geography at each stage: e.g., author, reviewer, editor by type
   
   + invited manuscripts by gender
   
   + submitted manuscripts by gender
   
   + geographically dominated categories? journals?

   
#Discussion
  + Summarize results
  
  + Compare to global micro stats (Elsiever Gender report)
  
  + compare proportions to ASM membership: 37% self-reported as F in 2012
  
  + impact of under rep in publication process (Leahey, 2007; )
  
  + Increasing awareness of diversity metrics & impacts on productivity/innovation

  + describe society health checklist - apply to journals (Potvin, 2018)
  
  + future directions
      + lay out forth coming papers to use this data to examine ASM peer review for gender & geographic bias
      + are female-authored papers handled differently from male-authored (number of revisions/decisions)
      + M/F reviewer/editor recommendations differ by gender of author/editor/reviewer
      + publication frequency & authorship prestige of M vs F 

#Data and Methods

###Data

All manuscripts handled by ASM journals (e.g., _mBio_, _Journal of Virology_) that recieved an editorial decision between January 1st, 2012 and August 31st, 2018 were supplied as XML files by ASM's publishing platform, eJP. Data were extracted from the XML documents provided using R statistical software (version 3.4.4) and the `XML` package (R citation). Data manipulation was handled using the `tidyverse`, `lubridate`, and `xml2` packages for R. Variables of interest included: the manuscript number assigned to each submission, manuscript type (e.g., full length research, erratum, editorial), category (e.g., microbial ecology), related (previously submitted) manuscripts, versions submitted, dates (e.g., submission, decision), author data (e.g., first, last, and corresponding authorships, total number of authors), reviewer data (e.g., reviewer score, recommendation, editor decision), and person data (names, institutions, country) of the editors, authors, and reviewers. 

It is common practice at ASM journals for manuscripts whose reviewers recommend extensive experimental revisions be given a decision of "reject with resubmission encouraged". If resubmitted, the authors are asked to note the previous (related) manuscript and the resubmission is assigned a new manuscript number. Multiple related manuscripts were tracked together by generating a unique grouped manuscript number based on the recorded related manuscript numbers. This grouped manuscript number served multiple purposes including: tracking a single manuscript through multiple rejections or transfers between ASM journals and to avoid duplicate counts of the same authors. 

###Gender prediction and assignment

The gender assignment API genderize.io was used to predict an indivdual's gender based on their given names, and country where possible. The genderize.io platform uses data gathered from social media to predict gender based on given names with the option to include an associated language or country to enhance the odds of succesful prediction. Since all manuscripts are submitted in English, we matched each individuals country against the list of X country names accepted by genderize.io. Using the `GenderGuesser` package for R, all unique given names associated with an accepted country were submitted to the genderize.io API and any names returned without a predictive assignment of either male or female were resubmitted without an associated country. All predictive assignments of either male or female are returned with a probability match of 0.50 or greater. The predicted genders of all given names (with and without an associated country) whose probabilities were greater or equal to our arbitrary success cut off of 0.65 were used to assign predicted gender to the individuals in our dataset. Predicted genders were assigned to individuals in the following order: first names and country, first names, middle names and country, middle names. The presenting gender (man/woman) of editors and senior editors in our dataset was hand validated using Google where possible. Individuals who were not assigned a gender are given values of "N/A" and referred to in the analysis as those with an "unclear" gender. 

###Data analysis and presentation

Data were visualized using the `ggplot` package for R.

#References
